@extends("layouts.admin")

@section("css")
    <style>
        .modal {
            display: none;
            position: fixed;
            inset: 0;
            background: rgba(0, 0, 0, 0.55);
            justify-content: center;
            align-items: center;
            z-index: 9999;
            transition: opacity 0.2s ease-out;
        }

        .modal-show {
            opacity: 1;
        }

        .modal-hide {
            opacity: 0;
        }

        .modal-content {
            background: white;
            width: 100%;
            max-width: 600px;
            padding: 20px;
            animation: fadeInUp .2s ease-out;
        }

        @keyframes fadeInUp {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }


    </style>
    <link rel="stylesheet" href="{{asset('css/data-table.min.css')}}">
    {{--    <link rel="stylesheet" href="{{asset('css/fontawesome.css')}}">--}}
    <link rel="stylesheet" href="{{asset('plugin/scroller.dataTables.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css"
          integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
@endsection

@section("content")
    <main>
        <section class="admin-container">
            <!-- Tags Section -->
            <div class="admin-section">
                <div class="admin-header">
                    <div>
                        <h2>Tags</h2>
                        <p>Manage Tags</p>
                    </div>
                    <button class="btn" id="addTagBtn">Add Tag</button>
                </div>

                <div class="admin-controls">
                    <input type="text" id="searchTags" placeholder="Search tags..."
                           class="admin-search">
                </div>
                <div class="overflow-x-auto">
                    <table id="{{$table_id}}" class="display nowrap w-full text-left">
                        <thead>
                        <tr>
                            <th>SN</th>
                            <th>Name</th>
                            <th>Key</th>
                            <th>Created At</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                    </table>
                </div>

            </div>

        </section>
    </main>

    <!-- Add/Edit Tag Modal -->
    <div class="modal h-full" id="tagModal">
        <div class="modal-content max-h-full overflow-y-auto">
            <div class="modal-header flex justify-between items-center mb-4">
                <h2 class="text-xl font-bold">Add Tag</h2>
                <button class="modal-close text-2xl font-bold" onclick="closeTagModal()">&times;</button>
            </div>

            <form id="tagForm" onsubmit="handleTagSubmit(event)" enctype="multipart/form-data">
                <!-- Name -->
                <div class="form-group mb-3">
                    <label for="tagName" class="block font-medium">Tag Name *</label>
                    <input type="text" id="tagName" name="name" required class="w-full px-3 py-2 border ">
                </div>

                <!-- Key -->
                <div class="form-group mb-3">
                    <label for="tagKey" class="block font-medium">Key</label>
                    <input id="tagKey" name="key" rows="3" class="w-full px-3 py-2 border "
                              placeholder="This field is autogenerated" readonly></input>
                </div>

                <!-- Slug -->
                <div class="form-group mb-3">
                    <label for="tagSlug" class="block font-medium">Slug</label>
                    <input type="text" id="tagSlug" name="slug" class="w-full px-3 py-2 border "
                           placeholder="This field is auto generated" readonly>
                </div>

                <!-- Actions -->
                <div class="form-group flex justify-end gap-3 mt-4">
                    <button type="button" class="btn btn-outline px-4 py-2" onclick="closeTag.Modal()">Cancel
                    </button>
                    <button type="submit" class="btn px-4 py-2">Add Tag</button>
                </div>
            </form>
        </div>
    </div>

@endsection

@section("js")
    <script src="{{asset('js/jquery.min.js')}}"></script>
    <script src="{{asset('js/data-table.min.js')}}"></script>
    <script src="{{asset('plugin/dataTables.scroller.min.js')}}"></script>
    @include("admin.includes.admin_index_script")
    @include("admin.tags.includes.script")
@endsection
